### ISSUE TITLE
snprintf

### ISSUE THREAD

**Issue by GDenisC** [HJfod/cocos-headers#22]
|Code  |Description                                                                                                                        |File|Line|
|-------|-----------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|-------|
|C1189|#error: Macro definition of snprintf conflicts with Standard Library function declaration|...\WindowsKits\10\Include\10.0.22000.0\ucrt\stdio.h|1914|

**Comment by HJfod** [comment]
This repository has been archived in favor of [Geode](https://github.com/geode-sdk/geode).
